In [8]:
import cv2 as cv
import numpy as np

star = cv.imread('star.png', 0)
_, thresh = cv.threshold(star, 100, 255, cv.THRESH_BINARY)

#cv.imshow('star', thresh)

contours, heirarchy = cv.findContours(thresh, cv.RETR_LIST, cv.CHAIN_APPROX_SIMPLE)
thresh = cv.cvtColor(star, cv.COLOR_GRAY2BGR)

star = cv.drawContours(thresh, contours, -1, (0, 0, 255), 2)
#cv.imshow('Contours', star)

print('Number of contours in the image = ', len(contours))
cnt = contours[0]

hull = cv.convexHull(cnt, returnPoints = False)
defects = cv.convexityDefects(cnt, hull)

print(defects)

cv.waitKey(0)
cv.destroyAllWindows()

Number of contours in the image =  1
[[[ 152  198  179 4525]]

 [[   0   50   23 4497]]

 [[  51  100   77 4598]]

 [[ 102  151  125 4510]]]
